FROM oraclelinux:7-slim

# Create app directory
WORKDIR /usr/src/oracledb_node

COPY . .

RUN yum update -y && \
  yum install -y oracle-release-el7 && \
  yum install -y oracle-nodejs-release-el7 && \
  yum install -y --disablerepo=ol7_developer_EPEL nodejs && \
  yum install -y oracle-instantclient19.3-basic.x86_64 && \
  yum clean all && \
  node --version && \
  npm --version && \
  npm install && \
  # npm install pm2 -g && \
  echo Installed

EXPOSE 6001

# CMD ["pm2-runtime", "ecosystem.config.js"]
CMD ["node", "server.js"]
# docker build -t migutak/oracledbnode:1.0.0 .

